#!/usr/bin/env php
<?php

use RoviTagger\RoviClient\Request\SearchRequest;
use RoviTagger\RoviClient\Response\Album;
use RoviTagger\RoviClient\Response\Artist;
use RoviTagger\RoviClient\Response\Genre;
use RoviTagger\RoviClient\Response\SearchResponse;
use RoviTagger\RoviClient\Response\SearchResult;
use RoviTagger\RoviClient\Response\Style;
use RoviTagger\RoviClient\RoviClient;

require_once __DIR__.'/../vendor/autoload.php';

/**
 * Proportion threshhold for duration matching.
 */
const THRESHHOLD = 0.1;

if (count($argv) < 3) {
    print "Usage: rovi-tagger <directory> <search term>\n";
    exit(1);
}

$config         = json_decode(file_get_contents(__DIR__.'/config.json'));
$directory      = $argv[1];
$imageFilenames = array();
$mp3Filenames   = array();
$albumDuration  = 0;
$dirIterator    = new RecursiveDirectoryIterator($directory);
$iterator       = new RecursiveIteratorIterator($dirIterator);

/** @var SplFileInfo $file */
foreach ($iterator as $file) {
    $filename = $file->getFilename();
    if ($filename[0] == '.') {
        // Ignore hidden files.
        continue;
    }
    $fileInfo = $file->getFileInfo();
    if ($fileInfo->getExtension() == 'jpg') {
        $imageFilenames[] = $file->getPath().'/'.$file->getBasename();
    }
    if ($fileInfo->getExtension() != 'mp3') {
        // Only process mp3 files.
        continue;
    }
    $mp3Filenames[] = $file->getPath().'/'.$file->getBasename();
    print "Determining duration of {$file->getFilename()}\n";
    $duration = (int) exec('mp3info -p "%S" '.escapeshellarg($file->getPath().'/'.$file->getBasename()));
    $albumDuration += $duration;
}
sort($mp3Filenames);

print "Album duration: $albumDuration\n";

$client = new RoviClient();
$client
    ->setApiKey($config->apiKey)
    ->setSecret($config->secret);

$searchRequest = new SearchRequest(
    'album',
    $argv[2],
    array('classicalReview', 'credits', 'tracks', 'styles')
);

/** @var SearchResponse $response */
$response = $client->getRequest($searchRequest);

/** @var Album[] $matchedAlbums */
$matchedAlbums = array();

/** @var SearchResult $result */
foreach ($response->results as $result) {
    $resultAlbumDuration = $result->album->duration;

    if ($resultAlbumDuration == 0) {
        foreach ($result->album->tracks as $track) {
            $resultAlbumDuration += $track->duration;
        }
    }

    print "Found album '{$result->album->title}' by '{$result->album->primaryArtists[0]->name}' with duration ".
        "{$resultAlbumDuration}";

    if (($resultAlbumDuration * (1 - THRESHHOLD)) <= $albumDuration &&
        ($resultAlbumDuration * (1 + THRESHHOLD)) >= $albumDuration &&
        count($result->album->tracks) == count($mp3Filenames)
    ) {
        $percentageMatch = number_format(
            100 - abs($resultAlbumDuration - $albumDuration) / $resultAlbumDuration * 100,
            2
        );

        print "\tMatched\t$percentageMatch%";

        if (isset($matchedAlbum[$percentageMatch])) {
            print "Multiple albums with same match percentage. Not supported.\n";
            exit(1);
        }

        $matchedAlbums[$percentageMatch] = $result->album;
    }

    print "\n";
}

if (count($matchedAlbums) === null) {
    print "No albums matched.\n";
    exit(1);
}

// Order by percentage descending - 100% being the closest match.
krsort($matchedAlbums);

$matchedAlbum = array_shift(array_values($matchedAlbums));

print "Using album {$matchedAlbum->title} by {$matchedAlbum->primaryArtists[0]->name}\n";

foreach ($mp3Filenames as $index => $file) {
    $track = $matchedAlbum->tracks[$index];

    $primaryArtistNames = array_map(
        function (Artist $artist) { return $artist->name; },
        $matchedAlbum->primaryArtists
    );
    $primaryArtistNames = implode(', ', $primaryArtistNames);
    if (empty($primaryArtistNames)) {
        $primaryArtistNames = 'Unknown Artist';
    }

    $performerNames = array_map(
        function (Artist $artist) { return $artist->name; },
        $track->performers
    );
    $performerNames = implode(', ', $performerNames);

    $composerNames = array_map(
        function (Artist $artist) { return $artist->name; },
        $track->composers
    );
    $composerNames = implode(', ', $composerNames);

    $genreNames = array_map(
        function (Genre $genre) { return $genre->name; },
        $matchedAlbum->genres
    );
    $genreNames = implode(', ', $genreNames);

    if (is_array($matchedAlbum->styles)) {
        $styleNames = array_map(
            function (Style $style) {
                return $style->name;
            },
            $matchedAlbum->styles
        );
        $styleNames = implode(', ', $styleNames);
    } else {
        $styleNames = '';
    }

    $classicalReviewText = isset($matchedAlbum->classicalReview) ? $matchedAlbum->classicalReview->text : '';

    preg_match('/[0-9]{4}/', $matchedAlbum->originalReleaseDate, $matches);
    $originalReleaseDateYear = (int) $matches[0];

    $tags = array(
        'album'         => array($matchedAlbum->title),
        'artist'        => array($performerNames),
        'band'          => array($primaryArtistNames),
        'comment'       => array($classicalReviewText),
        'genre'         => array(trim($genreNames.' - '.$styleNames, ' -')),
        'title'         => array(trim($track->part.' '.$track->title)),
        'track'         => array((int) $track->number),
        'part_of_a_set' => array((int) $track->disc),
        'year'          => array($originalReleaseDateYear),
    );

    $writer = new getid3_writetags();

    $writer->filename          = $file;
    $writer->tagformats        = array('id3v1', 'id3v2.4');
    $writer->overwrite_tags    = true;
    $writer->tag_encoding      = 'UTF-8';
    $writer->remove_other_tags = true;
    $writer->tag_data          = $tags;

    $writer->WriteTags();

    if (count($writer->errors)) {
        print "Error(s) tagging file {$file}:\n";
        foreach ($writer->errors as $error) {
            print "    {$error}\n";
        }
        exit(1);
    }

    if (!empty($config->directory)) {
        $sanitizedArtist = sanitizePath($primaryArtistNames);
        $sanitizedAlbum  = sanitizePath($matchedAlbum->title);
        $trackNumber     = str_pad($track->disc, 2, '0', STR_PAD_LEFT).'-'.str_pad($track->number, 3, '0', STR_PAD_LEFT);
        $sanitizedTitle  = sanitizePath($track->title);
        $newDirectory    = $config->directory.'/'.$sanitizedArtist.'/'.$sanitizedAlbum;
        $newFilename     = $newDirectory.'/'.$trackNumber.' - '.$sanitizedTitle.'.mp3';

        print "Moving {$file} to {$newFilename}\n";

        if (!is_dir($newDirectory)) {
            mkdir($newDirectory, 0777, true);
        }

        copy($file, $newFilename);
    }
}

// Now move all image files
if (!empty($config->directory)) {
    $sanitizedArtist = sanitizePath($primaryArtistNames);
    $sanitizedAlbum  = sanitizePath($matchedAlbum->title);
    $newDirectory    = $config->directory.'/'.$sanitizedArtist.'/'.$sanitizedAlbum;

    print "Moving {$file} to {$newFilename}\n";

    if (!is_dir($newDirectory)) {
        mkdir($newDirectory, 0777, true);
    }

    foreach ($imageFilenames as $imageFilename) {
        copy($imageFilename, $newDirectory.'/'.basename($imageFilename));
    }
}

print "Finished writing tags and moving files\n";

/**
 * Sanitize a filesystem path.
 *
 * @param string $path The path to sanitize.
 * @return string The sanitized path.
 */
function sanitizePath($path)
{
    return str_replace('/', '_', $path);
}
